### ISSUE TITLE
Quick question / Experience feedback

### ISSUE THREAD

**Issue by roscopecoltran** [m039/XLIS#1]
Hi Dmitry,

Hope you are all well !

**Context:**

I wanted to ask you a feedback about your cross-compilation experience as I am also working on some projects that would require to automatically generated unsafe bindings on some C/C++ projects. The difference with your experience is that I would like to create native plugins for Unity3D and not for Xamarin, and probably to build them with CMake. ^^ 

Actually, I am making some experiments with a couple of CMake macros, mainly to get all librairies properties (headers files list, define the expected library type per platforms like iOS (static lib) /Android (shared lib),... but I cannot test/forecast the worthiness of my efforts for a wider scope of integration.

**Some examples of C++ projects to bind on my wish list :**
- https://github.com/hunter-packages/opencv
- https://github.com/hunter-packages/dlib
   - I know a Unity Plugin for Dlib, for example, but I would like to develop a pattern that I can apply to some other libs.

     - https://github.com/ardevar/Mask/blob/master/Assets/DlibFaceLandmarkDetector/Scripts/DisposableDlibObject.cs
     - https://github.com/ardevar/Mask/blob/master/Assets/DlibFaceLandmarkDetector/Scripts/FaceLandmarkDetector.cs

**Question:**
So, I am not sure if it would be possible to automate in a reliable way the generation of native plugins for U3D with https://github.com/mono/CppSharp from the Mono team ? 

From your latest tests/experiments, would u see a way to automate such process with tools like [Hunter](https://github.com/ruslo/hunter)/[Polly](https://github.com/ruslo/polly) ?

Ps #1. I saw that you were familiar with Polly in some shell scripts.
Ps #2. Please find some references in order to save u some time of research on these topics. ^^

-----

**CMake driven examples of Unity Native Plugins (manually wrapped):**
- https://github.com/hellowod/unity-plugins-development
- https://github.com/mixpanel/mixpanel-unity (with SWIG)
- https://github.com/zillemarco/CppPlugGen (with CppSharp)
- https://github.com/zillemarco/CppSharp.CLI
- https://github.com/zillemarco/CppPlug

**Docs - Native Plugins for Unity3D **
- http://www.alanzucconi.com/2015/10/11/how-to-write-native-plugins-for-unity/
- https://docs.unity3d.com/Manual/AndroidNativePlugins.html
- https://docs.unity3d.com/Manual/PluginsForIOS.html

-----

Cheers,
Richard

**Comment by m039** [comment]
Hi, Richard!

CppSharp has some flaws that I've found and documented in [the related sample](https://github.com/m039/XLIS/tree/master/Cpp-Cross-Platform#notes). In short, CppSharp doesn't add MonoPInvokeCallbackAttribute to static functions that is need for iOS and I've added them manually [here](https://github.com/m039/XLIS/blob/master/Cpp-Cross-Platform/CSharpProjects/CppSharpSharedLibrary/CppFooBar.cs#L275). Also, you'll face a problem when you need to specify different dll name for iOS  and other platforms. Currently CppSharp can't do it either, I've added it manually too [here](https://github.com/m039/XLIS/blob/master/Cpp-Cross-Platform/CSharpProjects/CppSharpSharedLibrary/CppFooBar.cs#L15).

Otherwise I don't know any viable issue with CppSharp and I think it worth a try, but I haven't tried CppSharp since I wrote that sample.

Concerning Polly I think you may write a Unity Editor plugin which could make compilation for you (using Polly or any other tool), but I don't know much detail cause I have never written Unity Editor plugin yet.

I think to automate the process you should patch CppSharp to handle these issues or do some workaround.

**Comment by roscopecoltran** [comment]
Many thanks for your reply :-)

I have not think about to do it that way, will try it now :-)

And thanks for your examples ^^

**Comment by m039** [comment]
You're welcome :)
